export const memberColumns=[
    {title:"Member Id",fieldName:'member_id',field_type:'text',is_confidential:false},
    {title:"Member Name",fieldName:'name',field_type:'text',is_confidential:false},
    {title:"Member Created for",fieldName:'member_created_for',field_type:'text',is_confidential:false},
    {title:"Created Date",fieldName:'created_date',field_type:'date',is_confidential:false},
    {title:"Father Name",fieldName:'father_name',field_type:'text',is_confidential:false},
    {title:"Mother Name",fieldName:'mother_name',field_type:'text',is_confidential:false},
    {title:"Gender",fieldName:'gender',field_type:'text',is_confidential:false},
    {title:"Date of Birth",fieldName:'dob',field_type:'date',is_confidential:false},
    {title:"Age",fieldName:'age',field_type:'number',is_confidential:false},
    {title:"Marital Status",fieldName:'marital_status',field_type:'text',is_confidential:false},
    {title:"No. of Children",fieldName:'no_of_children',field_type:'number',is_confidential:false},
    {title:"Children Living Status",fieldName:'children_living_status',field_type:'text',is_confidential:false},
    {title:"Country",fieldName:'country',field_type:'text',is_confidential:false},
    {title:"State",fieldName:'state',field_type:'text',is_confidential:false},
    {title:"District",fieldName:'district',field_type:'text',is_confidential:false},
    {title:"Door No.",fieldName:'door_no',field_type:'text',is_confidential:false},
    {title:"Street",fieldName:'street',field_type:'text',is_confidential:false},
    {title:"Area",fieldName:'area',field_type:'text',is_confidential:false},
    {title:"Taluk",fieldName:'taluk',field_type:'text',is_confidential:false},
    {title:"Landmark",fieldName:'landmark',field_type:'text',is_confidential:false},
    {title:"Pincode",fieldName:'pincode',field_type:'text',is_confidential:false},
    {title:"Mobile No.",fieldName:'mobile_no',field_type:'text',is_confidential:false},
    {title:"Alternative Mobile 1",fieldName:'mobile_alt_no_1',field_type:'text',is_confidential:false},
    {title:"Alternative Mobile 2",fieldName:'mobile_alt_no_2',field_type:'text',is_confidential:false},
    {title:"Whatsapp No.",fieldName:'whatsapp_no',field_type:'text',is_confidential:false},
    {title:"Email Id",fieldName:'email',field_type:'text',is_confidential:false},
    {title:"Aadhaar No",fieldName:'aadhaar_no',field_type:'text',is_confidential:false},
    {title:"Religion",fieldName:'religion',field_type:'text',is_confidential:false},
    {title:"Caste",fieldName:'caste_name',field_type:'text',is_confidential:false},
    {title:"Sub Caste",fieldName:'sub_caste',field_type:'text',is_confidential:false},
    {title:"Caste Detail",fieldName:'caste_detail',field_type:'text',is_confidential:false},
    {title:"Languages Known",fieldName:'languages_known',field_type:'text',is_confidential:false},
    {title:"Gothra",fieldName:'gothra',field_type:'text',is_confidential:false},
    {title:"Kuladeivam",fieldName:'kuladeivam',field_type:'text',is_confidential:false},
    {title:"Poorveegam",fieldName:'poorveegam',field_type:'text',is_confidential:false},
    {title:"Residence Type",fieldName:'residence_type',field_type:'text',is_confidential:false},
    {title:"Willing to Home Mappillai",fieldName:'willing_to_home_mappilai',field_type:'boolean',is_confidential:false},
    {title:"Education",fieldName:'course_name',field_type:'text',is_confidential:false},
    {title:"Education Detail",fieldName:'education_detail',field_type:'text',is_confidential:false},
    {title:"Job Type",fieldName:'job_type',field_type:'text',is_confidential:false},
    {title:"Job",fieldName:'job_name',field_type:'text',is_confidential:false},
    {title:"Job Detail",fieldName:'job_detail',field_type:'text',is_confidential:false},
    {title:"Job Country",fieldName:'job_country',field_type:'text',is_confidential:false},
    {title:"Job State",fieldName:'job_state',field_type:'text',is_confidential:false},
    {title:"Job District",fieldName:'job_district',field_type:'text',is_confidential:false},
    {title:"Job Area",fieldName:'job_area',field_type:'text',is_confidential:false},
    {title:"Father Status",fieldName:'father_status',field_type:'boolean',is_confidential:false},
    {title:"Father Occupation",fieldName:'father_occupation',field_type:'text',is_confidential:false},
    {title:"Mother Status",fieldName:'mother_status',field_type:'boolean',is_confidential:false},
    {title:"Mother Occupation",fieldName:'mother_occupation',field_type:'text',is_confidential:false},
    {title:"No. of Brothers",fieldName:'brothers',field_type:'number',is_confidential:false},
    {title:"Married Brothers",fieldName:'brothers_married',field_type:'number',is_confidential:false},
    {title:"No. of Sisters",fieldName:'sisters',field_type:'number',is_confidential:false},
    {title:"Married Sisters",fieldName:'sisters_married',field_type:'number',is_confidential:false},
    {title:"Family Type",fieldName:'family_type',field_type:'text',is_confidential:false},
    {title:"Eating Habits",fieldName:'eating_habits',field_type:'text',is_confidential:false},
    {title:"Drinking Habits",fieldName:'drinking_habits',field_type:'text',is_confidential:false},
    {title:"Smoking Habits",fieldName:'smoking_habits',field_type:'text',is_confidential:false},
    {title:"Height(Cms)",fieldName:'height',field_type:'number',is_confidential:false},
    {title:"Weight(Kg)",fieldName:'weight',field_type:'number',is_confidential:false},
    {title:"Body Type",fieldName:'body_type',field_type:'text',is_confidential:false},
    {title:"Complexion",fieldName:'complexion',field_type:'text',is_confidential:false},
    {title:"Physical Status",fieldName:'physical_status',field_type:'text',is_confidential:false},
    {title:"Physical Details",fieldName:'physical_status_description',field_type:'text',is_confidential:false},
    {title:"Star",fieldName:'star',field_type:'text',is_confidential:false},
    {title:"Patham",fieldName:'patham',field_type:'text',is_confidential:false},
    {title:"Raasi",fieldName:'raasi',field_type:'text',is_confidential:false},
    {title:"Laknam",fieldName:'laknam',field_type:'text',is_confidential:false},
    {title:"Birth Time",fieldName:'birth_time',field_type:'text',is_confidential:false},
    {title:"Birth Place",fieldName:'birth_place',field_type:'text',is_confidential:false},
    {title:"Dhosam Type",fieldName:'dhosam_type',field_type:'text',is_confidential:false},
    {title:"Jadhagam Type",fieldName:'jadhagam_type',field_type:'text',is_confidential:false},
]